### ISSUE TITLE
Some TreeView thoughts and suggestions

### ISSUE THREAD

**Issue by sven5** [Lupusa87/LupusaBlazorProjects#15]
Hi @Lupusa87 
I didn't find your repo containing the TreeView component.
However I'd like to make some suggestions. You could extend your TreeView with some more functionality to become a helpful component. 
For instance, we're using the [bootstrap treeview widget](https://github.com/jonmiles/bootstrap-treeview) because Blazor lacks a treeview component. We need the following features:

- checkbox selection of nodes
- select all/deselect all through API
- extend all/hide all through API
- data-binding would be outstanding

For simplicity in a first step it would be enough to have a replacement for the bootstrap treeview widget.

Regards
Sven

**Comment by Lupusa87** [comment]
Hello @sven5 

Thank you for suggestions.

I was going to fully port my [TreeDataGrid](https://www.youtube.com/watch?v=UsguJr_VKD8) component which I have done in Silverlight.

As you can see it has lot's of features and needs significant effort and time to be done.

Because my time is very limited I decided to do this later, hopefully in close future :)

You can't see TreeView repo because it and some another repos are private for now.

I have some ongoing projects for now but if you can sponsor my work on TreeView I can do requested updates in following weeks.

For further communication please email me at VakhtangiAbashidze@gmail.com

Best Regards,
Vakhtangi Abashidze
