### ISSUE TITLE
BWHJsInterOp.IsReady Missing

### ISSUE THREAD

**Issue by tonyzaddo** [Lupusa87/LupusaBlazorProjects#23]
Hi, I like the look of your work and want to see if I can use some of your components in my project. If I do, I will certainly make a donation.

I am just having trouble getting the demo working. I have been trying to get it set up for about 4 hours. The demo repository doesn't include all the projects, so I have had to download this from the other repositories.

I am just stuck compiling the BlazorCalculatorComponent.  In CompBlazorCalculator.razor.cs it is attempting to use a property BHJsInterop.IsReady in BWHjsInterop.cs and method LocalStorageGetItem.  This property doesn't exist in the repository for BlazorWindowHelper and I can't find a new version elsewhere.  

Could you please update or send me code to include this property in the class. 

To get going, I am just using:
        private static bool _isReady = false;
        public static bool IsReady 
        { 
            get { return _isReady; } 
            set { _isReady = value; } 
        }

        public static ValueTask<string> LocalStorageGetItem(string id)
        {
            CheckHasJsRuntime();

            return jsRuntime.InvokeAsync<string>("return ''");
        }

Thx.

**Comment by Lupusa87** [comment]
Hello,

Thank you for reaching out.

Unfortunatelly I am busy this days and can't help you, my first child is
going to be born tomorrow.

I updated lately BWH and demos repo has old version.

You can remove isready check, but be sure to set jsruntime before using
BWHinterop methods.

You can get jsruntime instance from component and set it to bwhinterop.

Best place to do this is mainlayout component's oninitialize, because it
gets fired first on app load.

All referenced projects can be found on nuget and you can use them or from
github repos.

They have not to be in same repo because they are separated and independent
libraries.

I hope you will get it worked out.

My components aren't production ready, they were POCs and done on blazor's
early days, if you find them useful that's great.

Best Regards.
